
####################################################################################
# Generated by Vivado 2018.2 built on 'Thu Jun 14 20:03:12 MDT 2018' by 'xbuild'
# Command Used: write_xdc -no_fixed_only -force ./VivadoBuildOutput/fsm_impl.xdc
####################################################################################


####################################################################################
# Constraints from file : 'constraints_psk_sarma.xdc'
####################################################################################

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property PACKAGE_PIN U18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN U16 [get_ports O]
set_property IOSTANDARD LVCMOS33 [get_ports O]
set_property PACKAGE_PIN T17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN V17 [get_ports w]
set_property IOSTANDARD LVCMOS33 [get_ports w]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]



# Vivado Generated physical constraints 

set_property BEL B6LUT [get_cells {FSM_sequential_state[0]_i_1}]
set_property BEL A6LUT [get_cells {FSM_sequential_state[1]_i_1}]
set_property BEL BFF [get_cells {FSM_sequential_state_reg[0]}]
set_property BEL AFF [get_cells {FSM_sequential_state_reg[1]}]
set_property BEL OUTBUF [get_cells O_OBUF_inst]
set_property BEL AFF [get_cells O_reg]
set_property BEL A6LUT [get_cells O_reg_i_1]
set_property BEL B6LUT [get_cells O_reg_i_2]
set_property BEL INBUF_EN [get_cells clk_IBUF_inst]
set_property BEL INBUF_EN [get_cells reset_IBUF_inst]
set_property BEL INBUF_EN [get_cells w_IBUF_inst]
set_property LOC SLICE_X0Y5 [get_cells {FSM_sequential_state[0]_i_1}]
set_property LOC SLICE_X0Y5 [get_cells {FSM_sequential_state[1]_i_1}]
set_property LOC SLICE_X0Y5 [get_cells {FSM_sequential_state_reg[0]}]
set_property LOC SLICE_X0Y5 [get_cells {FSM_sequential_state_reg[1]}]
set_property LOC SLICE_X1Y5 [get_cells O_reg]
set_property LOC SLICE_X1Y5 [get_cells O_reg_i_1]
set_property LOC SLICE_X1Y5 [get_cells O_reg_i_2]
set_property LOC BUFGCTRL_X0Y0 [get_cells clk_IBUF_BUFG_inst]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
